#!/bin/bash
if [ -z "$1" ]
  then
    echo "This script requires two command line arguments, the version strings to compare"
	echo "usage: ./versionsorter 1.3.2.1 1.3.2.2"
	exit 0
fi
$JAVA_HOME/bin/java -cp $CLASSPATH com/versions/VersionSorter $1 $2
exit 0
